#!/bin/bash

ln -ivfs -T ~/.dotfiles/bashrc ~/.bashrc;
ln -ivfs -T ~/.dotfiles/vim ~/.vim;
ln -ivfs -T ~/.dotfiles/gitconfig ~/.gitconfig;
ln -ivfs -T ~/.dotfiles/profile ~/.profile;

## NOT WORKING ##
# loading files
#read -p "Load bashrc and profile? (Y/n): " confirm && [[ $confirm == "" || $confirm == [yY] || $confirm == [yY][eE][sS] ]] || (echo "h" && exit 1)
#source ~/.dotfiles/profile
#source ~/.dotfiles/bashrc
